class AppStrings {
  // General
  static const String appTitle = 'Good Gut App';
  static const String continueButton = 'Continue';
  // Gender Selection Screen
  static const String genderSelectionTitle =
      'Which gender do you more closely identify with?';
  static const String femaleLabel = 'Female';
  static const String maleLabel = 'Male';
  static const String genderSelectionNote =
      'Knowing your gender helps us customize your diet & exercise plans more accurately.';

  // Duration Selection Screen
  static const String durationSelectionTitle = 'How many times do you workout?';
  static const Map<int, dynamic> duration = {
    1: 'I don\'t',
    2: '1-3 times in a week',
    3: '3-5 times in a week',
    4: "6-7 times in a week",
    5: "More than 7 times in a week",
  };
  static const String durationSelectionNote =
      'Knowing your workout frequency helps us customize your diet & exercise plans more accurately.';

  // Food Selection Screen
  static const String foodSelectionTitle = 'What is your food preference?';
  static const Map<int, dynamic> food = {
    1: 'Vegetarian',
    2: 'Non-Vegetarian',
    3: 'Eggiterian',
    4: "Vegan",
  };
  static const String foodSelectionNote =
      'Knowing your food preference helps us customize your diet & exercise plans more accurately.';

  // Food Selection Screen
  static const String heightSelectionTitle = 'What is your height?';

  // Other Strings
  static const String skipButton = 'Skip';
  static const String stepIndicator = 'Step';

  static const String medicalSelectionNote =
      'This info will help us guide you to your fitness goals safely and quickly.';
  static const String occupationSelectionNote =
      'This will help us understand your lifestyle and recommend better options';

  static const String playStoreURL =
    'https://play.google.com/store/apps/details?id=com.upshrink.upsaver';
  static const String updateAvailable = 'Update Available';
  static const String updateMessage =
      'A new version of the app is available. Please update to continue using the app.';
  static const String update = 'Update';
  static const String cancel = 'Cancel';

  static const String apiURL = "http://127.0.0.1:3000/api";
  
  static const String versionUrl = "/version";
  static const String loginURL = "/login";
  static const String flyerURL = "/flyer";
  static const String faqURL = "/faq";
  static String get productsURL => "$apiURL/products";

  // Jitsi Meet — room names are generated by the API per call id
  static const String jitsiDomain = "meet.jit.si";
}
